In [1]:
# !/home/jedi/.pyenv/37venv/bin/python3.7 -m pip install manim
# !/home/jedi/.pyenv/37venv/bin/python3.7 -m pip install --upgrade pip

In [2]:
from manim import *

vmobject init:  [[ 0.54030231 -0.84147098  0.        ]
 [ 0.61042489 -0.79644579  0.        ]
 [ 0.67488564 -0.74261283  0.        ]
 [ 0.73168887 -0.68163876  0.        ]
 [ 0.73168887 -0.68163876  0.        ]]


Manim Community v0.11.0

In [3]:
%%manim -qm -v ERROR --flush_cache RecursiveCode

# recursive code viz

class RecursiveCode(Scene):
    def construct(self):
        # Show opening

        # show code
        code = '''
#!/bin/python

def func(x):
    # ...
    func(x)
'''
        code_mbj = Code(code=code, language="python", tab_width=4, insert_line_no=False, background="window", font="Monospace")
        code_mbj.scale_to_fit_width(7)

        self.play(Write(code_mbj))
        self.wait(1.5)

        # highlight recursive call
        self.play(code_mbj.code[4][:].animate.set_color(YELLOW))
        self.play(Indicate(code_mbj.code[4][:], color=WHITE))
        self.play(code_mbj.code[4][:].animate.set_color(WHITE))
        self.wait(1.5)

        # remove code
        self.play(Uncreate(code_mbj))
        self.wait(1.5)


vmobject init:  []
vmobject init:  []
vmobject init:  [[ 4.06250000e-01  3.04638706e-33  4.97512762e-17]
 [ 4.06250000e-01  8.12500000e-01 -4.97512762e-17]
 [ 4.06250000e-01  1.62500000e+00 -1.49253829e-16]
 [ 4.06250000e-01  2.43750000e+00 -2.48756381e-16]
 [ 4.06250000e-01  2.43750000e+00 -2.48756381e-16]]
vmobject init:  []
vmobject init:  []
vmobject init:  [[3.03125000e+00 2.71875000e+00 3.82702125e-17]
 [2.95833333e+00 2.37500000e+00 7.14377300e-17]
 [2.88541667e+00 2.03125000e+00 1.04605247e-16]
 [2.81250000e+00 1.68750000e+00 1.37772765e-16]
 [2.81250000e+00 1.68750000e+00 1.37772765e-16]]
vmobject init:  []
vmobject init:  []
vmobject init:  [[2.25000000e+00 1.29687500e+00 1.16724148e-16]
 [2.08854167e+00 1.29687500e+00 9.69512049e-17]
 [1.92708333e+00 1.29687500e+00 7.71782618e-17]
 [1.76562500e+00 1.29687500e+00 5.74053187e-17]
 [1.76562500e+00 1.29687500e+00 5.74053187e-17]]
vmobject init:  []
vmobject init:  []
vmobject init:  [[ 3.75000000e-01 -6.25000000e-02  5.35782975e

KeyboardInterrupt: 

In [ ]:
%%manim -qm -v ERROR RecursiveProperties

# recursive properties viz

class RecursiveProperties(MovingCameraScene):
    def construct(self):
        # declare big square
        sqr_big = Square(side_length=2.5)
        sqr_big.set_fill(BLUE_E, opacity=1)
        sqr_big_label = MathTex("X", tex_to_color_map={"text": WHITE})
        sqr_big_label.scale_to_fit_width(1.5)

        vg1 = VGroup(
            sqr_big,
            sqr_big_label
        )

        # declare square with label
        sqr_sml = Square(side_length=1.5)
        sqr_sml.set_fill(BLUE_E, opacity=1)
        sqr_sml_label = MathTex("X", tex_to_color_map={"text": WHITE})
        sqr_sml_label.scale_to_fit_width(0.75)

        vg2 = VGroup(
            sqr_sml,
            sqr_sml_label
        )

        self.play(Create(vg1))
        self.wait()

        # move square down
        self.play(vg1.animate.to_edge(DOWN, LARGE_BUFF * 2))
        self.wait()

        # Show 2 properties labels
        lbl1 = Tex(r"Propriedade 1.\\*", r"Simetria interna.")
        lbl1.scale(1.5).to_edge(UL)

        lbl2 = Tex(r"Propriedade 2.\\*", r"Caso base.")
        lbl2.scale(1.5).to_edge(UR)

        self.play(Write(lbl1))
        self.wait()

        # indicate little square
        vg1.set_z_index(1)
        vg2.set_z_index(0)

        vg2.move_to(vg1.get_center())

        self.add(vg2)
        self.play(vg2.animate.shift(1.2 * UP))
        self.wait(1.8)

        self.play(Indicate(vg2))
        self.wait()

        # show second label
        self.play(Write(lbl2))
        self.wait()
        self.play(Unwrite(lbl1), run_time=0.8)
        self.play(lbl2.animate.to_edge(UL))
        self.wait()

        # tiny square with label
        sqr_tiny = Square(side_length=0.5)
        sqr_tiny.set_fill(BLUE_E, opacity=1)
        sqr_tiny_label = MathTex("X", tex_to_color_map={"text": WHITE})
        sqr_tiny_label.scale_to_fit_width(0.15)

        vg3 = VGroup(
            sqr_tiny,
            sqr_tiny_label
        )

        # main arrow
        tex_arrow1 = MathTex(r"\rightarrow")
        tex_arrow1.scale_to_fit_width(2).to_edge(DOWN, LARGE_BUFF * 2)

        tex_arrow2 = MathTex(r"\rightarrow ...")
        tex_arrow2.scale_to_fit_width(2.8).to_edge(DOWN, LARGE_BUFF * 2)

        tex_arrow3 = MathTex(r"\rightarrow")
        tex_arrow3.scale_to_fit_width(1).to_edge(DOWN, LARGE_BUFF * 2)

        arrows = [tex_arrow1, tex_arrow2, tex_arrow3]

        # separate them
        new_origin = [0, vg1.get_y(), 0]
        self.play(vg1.animate.to_edge(LEFT),
            vg2.animate.move_to(new_origin),
            vg3.move_to(new_origin).animate.to_edge(RIGHT))

        tex_arrow1.move_to(vg1.get_center() + RIGHT * 3)
        tex_arrow2.move_to(vg2.get_center() + RIGHT * 2.5)
        tex_arrow3.move_to(tex_arrow2.get_center() + RIGHT * 2.5)

        self.play(Write(tex_arrow1), Write(tex_arrow2), Write(tex_arrow3))
        self.wait()

        self.play(sqr_tiny.animate.set_color(GREEN))
        self.play(Flash(vg3))
        self.wait()

        self.play(
            *[FadeOut(arrow) for arrow in arrows],
            FadeOut(vg1),
            FadeOut(vg2),
            FadeOut(vg3),
        )
        self.wait()


In [ ]:
%%manim -qm -v ERROR ExemploFatorial

# recursive problem viz

class ExemploFatorial(Scene):
    def construct(self):
        tex_rec = Text("Fatorial", color=WHITE)
        tex_rec.scale_to_fit_width(config["frame_width"] - 2 * LARGE_BUFF)

        self.play(Write(tex_rec))
        self.wait()

        fat_tex = MathTex(
           r"\left\{\begin{array}{ll}n > 0: & n! = n\cdot(n - 1)! \\ n = 0: & n! = 1 \end{array} \right."
        )
        # fat_tex.align_to(LEFT)
        fat_tex.scale_to_fit_width(config["frame_width"] - 2 * LARGE_BUFF)
        # fat_tex.arrange_in_grid(cols=1, cell_alignment=LEFT)

        self.play(Transform(tex_rec, fat_tex))
        self.wait(5)

        code = '''
unsigned int fatorial(unsigned int n) {
    /// caso base
    if(n == 0) return 1;

    /// passo de recursão
    return n * fatorial(n - 1);
}
'''
        code_mbj = Code(code=code, language="C", tab_width=4, insert_line_no=False, background="window", font="Monospace")
        code_mbj.scale_to_fit_width(12)

        self.play(Transform(tex_rec, code_mbj))
        self.wait()


In [ ]:
%%manim -ql -v WARNING FatorialExplanation

class FatorialExplanation(Scene):
    def construct(self):
        code = '''
unsigned int fatorial(unsigned int n) {
    /// caso base
    if(n == 0) return 1;

    /// passo de recursão
    return n * fatorial(n - 1);
}
'''
        code_mbj = Code(code=code, language="C", tab_width=4, insert_line_no=False, background="window", font="Monospace")
        code_mbj.scale_to_fit_width(12)
        self.add(code_mbj)

        self.play(Indicate(code_mbj.code[1][4:17]))
        self.wait()

        self.play(Indicate(code_mbj.code[2][7:13]))
        self.wait()

        self.play(Indicate(code_mbj.code[5][14:30]))
        self.wait()

        self.play(Indicate(code_mbj.code[5][24:29]))
        self.wait()



In [ ]:
%%manim -ql -v WARNING ExpandingFactorial

class ExpandingFactorial(Scene):
    def construct(self):
        # show equation with n
        math_tex = MathTex(r"n!", substrings_to_isolate="!")
        math_tex.scale_to_fit_height(1.5)

        self.play(Write(math_tex))
        # self.wait()
        
        # n! =
        fact_lhs, fact_rhs = (r"n! = ", r"")
        math_tex_new = MathTex(fact_lhs + fact_rhs)
        math_tex_new.scale_to_fit_height(1.1)
        math_tex_new.to_edge(LEFT)

        self.play(math_tex.animate.to_edge(LEFT), ReplacementTransform(math_tex, math_tex_new))
        # self.wait()
        
        math_tex = math_tex_new

        # 5! =
        fact_lhs, fact_rhs = (r"5! =", r"")
        math_tex_new = MathTex(fact_lhs + fact_rhs, substrings_to_isolate="=")
        math_tex_new.scale_to_fit_height(1.1)
        math_tex_new.to_edge(LEFT)

        self.add(math_tex)
        self.play(ReplacementTransform(math_tex, math_tex_new))
        # self.wait()
        self.add(math_tex)
        self.remove(math_tex)

        math_tex = math_tex_new

        # 5! = 5!
        fact_lhs, fact_rhs = (r"5! = ", r"5!")
        math_tex_new = MathTex(fact_lhs + fact_rhs, substrings_to_isolate=("=", "!"))
        math_tex_new.scale_to_fit_height(1.1)
        math_tex_new.to_edge(LEFT)

        self.add(math_tex)
        self.play(ReplacementTransform(math_tex[-1], math_tex_new[-3:]))
        # self.wait()
        self.add(math_tex)
        self.remove(math_tex)

        math_tex = math_tex_new

        # 5! = rest of equation
        for i in reversed(range(5)):
            fact_rhs = fact_rhs.replace('!', r" \cdot " + str(i) + r"!")

            math_tex_new = MathTex(fact_lhs + fact_rhs, substrings_to_isolate=("=", "\cdot", "!"))
            math_tex_new.scale_to_fit_height(1.1)
            math_tex_new.to_edge(LEFT)

        #     print(math_tex.submobjects)
        #     print(math_tex_new.submobjects)

            self.add(math_tex)
            self.play(ReplacementTransform(math_tex[-1], math_tex_new[-3:]))
            # self.wait()
            self.add(math_tex)
            self.remove(math_tex)

            math_tex = math_tex_new
        
        # indicate 0!
        self.add(math_tex)
        self.play(Indicate(math_tex[-2:]))
        self.wait()

        # 0! => 1
        fact_rhs = fact_rhs.replace('0!', '1')
        math_tex_new = MathTex(fact_lhs + fact_rhs, substrings_to_isolate=("=", "\cdot", "!"))
        math_tex_new.scale_to_fit_height(1.1)
        math_tex_new.to_edge(LEFT)

        # print(math_tex.submobjects)
        # print(math_tex_new.submobjects)
        
        self.add(math_tex)
        self.play(ReplacementTransform(math_tex[-2:], math_tex_new[-1:]))
        self.wait()
        self.add(math_tex)
        self.remove(math_tex)
        
        # self.remove(math_tex_new)
        math_tex = math_tex_new

        # get result
        fact_rhs = r"{{120}}"
        math_tex_new = MathTex(fact_lhs + fact_rhs, substrings_to_isolate=("=", "\cdot", "!"))
        math_tex_new.scale_to_fit_height(1.1)
        math_tex_new.to_edge(LEFT)

        self.add(math_tex)
        self.play(ReplacementTransform(math_tex[4:], math_tex_new[-1]))
        self.wait()
        self.add(math_tex)
        self.remove(math_tex)

        math_tex = math_tex_new



In [ ]:
%%manim -ql -v WARNING HammerNails

class HammerNails(Scene):
    def construct(self):
        hammer = SVGMobject('./vizus_files/hammer.svg')
        hammer.move_to(UP * 2 + LEFT * 4)

        self.play(FadeIn(hammer))
        self.wait()

        nail = SVGMobject('./vizus_files/nail.svg')
        cube = SVGMobject('./vizus_files/cube.svg')
        screw = SVGMobject('./vizus_files/screw.svg')
        pyramids = SVGMobject('./vizus_files/pyramids.svg')

        prob_mobjs = VGroup(nail, cube, screw, pyramids).scale(0.7).arrange(buff=1.0).move_to(DOWN * 2 + RIGHT * 2)

        self.play(FadeIn(prob_mobjs))

        self.play(Transform(cube, nail.copy().move_to(cube)))

        self.play(Transform(screw, nail.copy().move_to(screw)))

        self.play(Transform(pyramids, nail.copy().move_to(pyramids)))
        self.wait()



In [ ]:
%%manim -qm -v WARNING CountingScene

class Count(Animation):
    def __init__(self, number: DecimalNumber, start: float, end: float, **kwargs) -> None:
        # Pass number as the mobject of the animation
        super().__init__(number,  **kwargs)
        # Set start and end
        self.start = start
        self.end = end

    def interpolate_mobject(self, alpha: float) -> None:
        # Set value of DecimalNumber according to alpha
        value = self.start + (self.rate_func(alpha) * (self.end - self.start))
        self.mobject.set_value(value)

class CountingScene(Scene):
    def construct(self):
        # Create Decimal Number and add it to scene
        number = DecimalNumber().set_color(WHITE).scale(5)
        # Add an updater to keep the DecimalNumber centered as its value changes
        number.add_updater(lambda number: number.move_to(ORIGIN))

        self.play(FadeIn(number))
        self.wait()

        self.play(Count(number, 0, 10), run_time=10, rate_func=rate_functions.linear)
        self.wait()

In [ ]:
%%manim -qm -v WARNING Clarity

class Clarity(Scene):
    """ Cena de alguém tendo as dúvidas sanadas """
    
    def construct(self):
        head = SVGMobject('./vizus_files/head.svg').flip().move_to(DOWN * 1.5 + LEFT * 3.8).scale(1.7)

        self.play(FadeIn(head))
        # self.wait()

        talk_baloons = []
        baloon_positions = [DOWN * 1.4 + LEFT * 1.2, DOWN + RIGHT * 0.9, UP * 0.7 + LEFT * 0.6, UP * 1.1 + RIGHT * 1.4]
        for i in range(4):
            talk_baloon = SVGMobject('./vizus_files/talk-baloon.svg').move_to(baloon_positions[i])
            baloon_text = Text("?", color=BLACK, stroke_width=5).move_to(talk_baloon).scale(2)

            talk = VGroup(talk_baloon, baloon_text)

            self.play(FadeIn(talk_baloon), run_time=0.6)
            # self.wait()
            self.play(Write(baloon_text), run_time=0.6)
            # self.wait()

            talk_baloons.append(talk)

        self.play(Flash(head.get_center() + UP * 0.6 + LEFT * 0.1, flash_radius=0.4))
        self.wait()

        for talk in talk_baloons:
            talk_baloon, baloon_text = talk
            exc_mark = Text("!", color=BLACK, stroke_width=5).move_to(talk_baloon).scale(2)

            self.play(Transform(baloon_text, exc_mark), run_time=0.6)
            # self.wait()

In [ ]:
%%manim -qm -v WARNING FortranRecursion

class FortranRecursion(Scene):
	""" FORTRAN e recursão """

	def construct(self):
		code_icon = SVGMobject('./vizus_files/code.svg')

		self.play(FadeIn(code_icon))
		self.wait()

		code = """
! FORTRAN

PROGRAM HELLO
	PRINT *, "HELLO WORLD!"
END
"""

		code_fortran = Code(code=code, language="fortran", tab_width=4, insert_line_no=False, background="window", font="Monospace")
		code_fortran.scale_to_fit_width(12.0)

		self.play(Transform(code_icon , code_fortran[0]))
		self.play((Write(code_fortran)))
		self.wait()

		code = """
RECURSIVE FUNCTION factorial(n) RESULT (res)
    integer, intent(in) :: n
    integer :: res

    if (n <= 0) THEN
            res = 1
    ELSE
            res = factorial(n-1) * n
    END IF

END FUNCTION fac
"""

		code_fortran_factorial = Code(code=code, language="fortran", tab_width=4, insert_line_no=False, background="window", font="Monospace")
		code_fortran_factorial.scale_to_fit_width(12.0)

		self.play(Transform(code_fortran, code_fortran_factorial[0]))
		self.play(Write(code_fortran_factorial), run_time=5.0)
		self.wait()


In [ ]:
%%manim -qm -v WARNING StackIntroduction

class StackIntroduction(Scene):
    """  """

    def construct(self):
        self.wait()


In [40]:
from manim import *

config.media_width = "60%"

In [73]:
%%manim -qm -v WARNING --flush_cache EyeRoll

import numpy
from svgpathtools import parse_path

class EyeLook(Animation):
    def __init__(self, eye_mobject: Mobject, end_look_vector: numpy.ndarray, start_look_vector: numpy.ndarray=ORIGIN, rate_func=rate_functions.smooth,
        **kwargs) -> None:
        super().__init__(eye_mobject, **kwargs)

        self.end_look_vector = end_look_vector
        self.start_look_vector = start_look_vector

        self.rate_func = rate_func

        self.lid_points = parse_path(self.mobject.lids.path_string)
        print(self.lid_points)
        # print(self.lid_points.d())

        self.path_string_config = { }

    def interpolate_mobject(self, alpha: float) -> None:
        value = self.start_look_vector + (self.rate_func(alpha) * (self.end_look_vector - self.start_look_vector))
        value *= self.mobject.scale_factor/10

        # print(value[0])

        self.mobject.iris.move_to(value)
        self.mobject.shift_upper_lid(value)
        # self.lid_points[1] = self.lid_points[1].translated(-0.1+0j)
        # self.lid_points[2] = self.lid_points[2].translated(-4+0j)

        self.mobject.regenerate_lid()
        # self.mobject.regenerate_lid("m 101.9834,154.8058 c 0,0 0.10223,-8.28072 22.39633,-8.27392 22.2942,0.007 36.99157,8.27392 36.99157,8.27392 0,0 -14.62987,9.87678 -36.99157,9.76768 -22.3616,-0.1091 -22.39633,-9.76768 -22.39633,-9.76768 z")

class EyeLit(SVGMobject):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    
        self.eyelit_height = self.height
        self.eyelit_width = self.width

        self.eyeball = self.submobjects[0]
        self.lids = self.submobjects[1]
        self.iris = self.submobjects[2]

        self.lid_points = self.lids.get_original_path_string()
        self.lids_height = self.lids.height
        self.lids_width = self.lids.width

    def generate_points(self):
        return super().generate_points()
    
    def scale(self, scale_factor: float, **kwargs) -> "Mobject":
        self.scale_factor = scale_factor
        print(self.scale_factor)
        return super().scale(scale_factor, **kwargs)
    
    def regenerate_lid(self):
        self.lids.set(path_string=self.lid_points.d())

        self.lids.reset_points()
        self.lids.generate_points()
        self.lids.init_colors()

        self.lids.center()

        self.lids.height = self.lids_height
        self.lids.width = self.lids_width
        self.lids.scale(self.scale_factor)
    
    def shift_upper_lid(self, move_vec):
        upper_lid_curves = self.lids[:2]
        upper_lid_curves[0]
        print(upper_lid_curves)

class EyeRoll(Scene):
    def construct(self):
        M_A = "M 101.9834 154.8058 C 101.9834 154.8058 109.3832 145.7782 121 146 C 153.9715 145.792 161.3713 154.8058 161.3713 154.8058 C 161.3713 154.8058 154.039 163.9357 121 164 C 109.3157 163.7175 101.9834 154.8058 101.9834 154.8058 Z"
        M_S = "m 101.9834,154.8058 c 0,0 1.0447,-9.0276 23.3388,-9.0208 22.2942,0.007 36.0491,9.0208 36.0491,9.0208 0,0 -13.6874,9.1299 -36.0491,9.0208 -22.3616,-0.1091 -23.3388,-9.0208 -23.3388,-9.0208 z"

        print(parse_path(M_S))

        eyelit = EyeLit(file_name="./vizus_files/eyelit.svg").scale(3.0)
        # lid = SVGMobject("./vizus_files/lid.svg")
        # print(eyelit[1].get_original_path_string())
        # print(eyelit[1].points[:5])

        # print(eyelit.height, eyelit.width)

        # height = eyelit[1].height
        # width = eyelit[1].width

        # lid = SVGPathMobject(path_string=M_S, **{}, **{'fill_opacity': 1.0, 'stroke_opacity': 1.0, 'fill_color': '#ffffff', 'stroke_width': 0, 'stroke_color': '#ffffff'})
        # lid.height = 2
        # lid.center()

        # eyelit[1].set(path_string="m 101.9834,154.8058 c 0,0 0.10223,-8.28072 22.39633,-8.27392 22.2942,0.007 36.99157,8.27392 36.99157,8.27392 0,0 -14.62987,9.87678 -36.99157,9.76768 -22.3616,-0.1091 -22.39633,-9.76768 -22.39633,-9.76768 z")
        # eyelit[1].reset_points()
        # eyelit[1].generate_points()
        # eyelit[1].init_colors()
        # eyelit[1].center()
        # eyelit[1].height = height
        # eyelit[1].width = width

        # self.add(eyelit)
        # self.add(lid)

        self.play(EyeLook(eyelit, [-1.0, -1.0, 0]), run_time=1, rate_func=rate_functions.smooth)


Path(CubicBezier(start=(101.9834+154.8058j), control1=(101.9834+154.8058j), control2=(103.02810000000001+145.7782j), end=(125.32220000000001+145.785j)),
     CubicBezier(start=(125.32220000000001+145.785j), control1=(147.6164+145.792j), control2=(161.37130000000002+154.8058j), end=(161.37130000000002+154.8058j)),
     CubicBezier(start=(161.37130000000002+154.8058j), control1=(161.37130000000002+154.8058j), control2=(147.68390000000002+163.9357j), end=(125.32220000000001+163.8266j)),
     CubicBezier(start=(125.32220000000001+163.8266j), control1=(102.96060000000001+163.7175j), control2=(101.98340000000002+154.8058j), end=(101.98340000000002+154.8058j)),
     Line(start=(101.98340000000002+154.8058j), end=(101.9834+154.8058j)))
0.022872024049475848
3.0
Path(CubicBezier(start=(101.9834+154.8058j), control1=(101.9834+154.8058j), control2=(109.3832+145.7782j), end=(131.6773+145.785j)),
     CubicBezier(start=(131.6773+145.785j), control1=(153.9715+145.792j), control2=(161.3713+154.8058j),

Animation 0: EyeLook(EyeLit):  37%|███▋      | 11/30 [00:00<00:00, 106.87it/s]

VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects
VGroup of 1 submobjects


VGroup of 1 submobjects
VGroup of 1 submobjects
